import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * THE MASTER-WORKBOOK LOADER — Phase 0 of docs/HEALTH-ASSIST-APPROACH.md.
 *
 * Reads what `scripts/import-health-workbook.mjs` transcribed from the SAOS rule
 * workbook (rules/workbook/sheets), plus the hand-maintained layers beside it:
 *   profiles.json      modules, dimensions, group → dimension, weight status
 *   overlays/*.json    engineering fields per rule (decision D-007)
 *   params/*.json      parameter declaration status per rule
 *   ownership.json     one owner per condition that several sheets restate (D-003)
 *   legacy-map.json    the hard-coded rules against their workbook counterparts
 *   decisions.json     the decisions the rest refers to
 *   deviations.json    code vs workbook, generated by scripts/health-workbook-audit.mjs
 *
 * PHASE 0: NOTHING IMPORTS THIS YET. The running engine is unchanged; Phase 1
 * builds the module registry and parameter registry on top of it. It lives
 * outside the engine hash (incremental.js ENGINE_FILES does not match it, and
 * rules/workbook/ is not catalogue/), so adding it moved no module's engine key.
 *
 * `validateWorkbook()` never throws. It reports:
 *   errors   inconsistencies that must not ship: a group with no dimension, an
 *            overlay entry for a rule that does not exist, a Systemic role on a
 *            non-Systemic rule, a stale overlay after a re-import …
 *   pending  work still to do: unreviewed overlay entries, Systemic rules with no
 *            role, undeclared parameters, open ownership conditions. In strict
 *            mode (from Phase 2) pending items are errors.
 */

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const WORKBOOK_DIR = path.join(HERE, 'rules', 'workbook');

export const SEVERITY_WORDS = Object.freeze(['Systemic', 'Critical', 'High', 'Moderate', 'Low']);
export const RULE_KINDS = Object.freeze(['record', 'rate', 'configuration', 'trend', 'correlation', 'context']);
export const ATTAINMENTS = Object.freeze(['binary', 'good_share', 'bad_rate', 'record_deduction', 'none']);
export const SYSTEMIC_ROLES = Object.freeze(['blocker', 'defect', 'posture', 'derived']);
export const IMPLEMENTATION_STATES = Object.freeze(['built', 'not_built']);
export const PARAM_STATUSES = Object.freeze(['DECLARED', 'UNDECLARED']);

const readJson = (dir, rel) => JSON.parse(fs.readFileSync(path.join(dir, rel), 'utf8'));

/** Everything under rules/workbook/, parsed. */
export function loadWorkbook(dir = WORKBOOK_DIR) {
  const source = readJson(dir, 'source.json');
  const sheets = {};
  const overlays = {};
  const params = {};
  for (const key of Object.keys(source.sheets)) {
    sheets[key] = readJson(dir, source.sheets[key].file);
    overlays[key] = readJson(dir, `overlays/${key}.json`);
    params[key] = readJson(dir, `params/${key}.json`);
  }
  return {
    dir,
    source,
    schema: readJson(dir, 'schema.json'),
    sheets,
    overlays,
    params,
    profiles: readJson(dir, 'profiles.json'),
    ownership: readJson(dir, 'ownership.json'),
    legacyMap: readJson(dir, 'legacy-map.json'),
    decisions: readJson(dir, 'decisions.json'),
    deviations: fs.existsSync(path.join(dir, 'deviations.json')) ? readJson(dir, 'deviations.json') : null,
  };
}

/** Every workbook rule of a module, with its overlay and parameter entries. */
export function workbookRules(wb, moduleKey) {
  const out = [];
  for (const [key, sheet] of Object.entries(wb.sheets)) {
    for (const r of sheet.rules) {
      const o = wb.overlays[key].rules[r.id];
      if (o?.module === moduleKey) out.push({ sheet: key, rule: r, overlay: o, params: wb.params[key].rules[r.id] });
    }
  }
  return out;
}

/** The dimension keys a module may use, from its profile (and the workbook, for data-quality models). */
export function moduleDimensions(wb, moduleKey) {
  const m = wb.profiles.modules.find((x) => x.key === moduleKey);
  if (!m) return null;
  if (m.dimension_source) {
    const model = wb.sheets[m.dimension_source.sheet]?.models?.find((x) => x.model === m.dimension_source.model);
    return model ? model.dimensions.map((d) => ({ key: d.key, label: d.label, weight: d.weight, weight_source: 'workbook' })) : null;
  }
  return (m.dimensions || []).map((d) => ({ key: d.key, label: d.label, weight: null, weight_source: m.weights_status, scored: d.scored !== false }));
}

export function validateWorkbook(wb = loadWorkbook(), { strict = false } = {}) {
  const errors = [];
  const pending = { unreviewed_overlays: 0, systemic_without_role: [], undeclared_parameters: 0, open_ownership: [], orphans: [] };
  const err = (m) => errors.push(m);
  const sha = wb.source.workbook_sha256;

  const ruleIndex = new Map();
  const moduleKeys = new Set(wb.profiles.modules.map((m) => m.key));

  /* ── sheets ── */
  for (const [key, sheet] of Object.entries(wb.sheets)) {
    if (sheet.source?.workbook_sha256 !== sha) err(`sheets/${key}.json was imported from a different workbook than source.json`);
    if (sheet.rules.length !== wb.source.sheets[key].rules) err(`sheets/${key}.json holds ${sheet.rules.length} rules; source.json says ${wb.source.sheets[key].rules}`);
    sheet.rules.forEach((r, i) => {
      const expected = `${sheet.id_prefix}-${String(i + 1).padStart(3, '0')}`;
      if (r.id !== expected) err(`${key}: rule ${i + 1} is ${r.id}, expected ${expected}`);
      /* Phase 9: a rule the source states with no band (CSDM-072, "Composite") is declared on its sheet, with the wording kept. */
      const exempt = r.base_severity == null && sheet.severity_exempt?.[r.id];
      if (!exempt && !SEVERITY_WORDS.includes(r.base_severity)) err(`${r.id}: base severity "${r.base_severity}" is not a workbook band`);
      if (ruleIndex.has(r.id)) err(`${r.id} appears in two sheets`);
      ruleIndex.set(r.id, { sheet: key, rule: r });
    });
  }

  /* ── profiles: every group of a by-group module maps to exactly one dimension ── */
  for (const m of wb.profiles.modules) {
    for (const s of m.sheets) {
      if (!wb.sheets[s.sheet]) err(`profile ${m.key}: sheet "${s.sheet}" was not imported`);
      else if (s.model && !wb.sheets[s.sheet].models?.some((x) => x.model === s.model)) err(`profile ${m.key}: model "${s.model}" is not in sheet ${s.sheet}`);
    }
    if (m.dimension_source && !moduleDimensions(wb, m.key)) err(`profile ${m.key}: dimension source ${JSON.stringify(m.dimension_source)} not found`);
    if (m.dimension_assignment !== 'by_group') continue;
    const keys = new Set();
    const mapped = new Map();
    for (const d of m.dimensions || []) {
      if (keys.has(d.key)) err(`profile ${m.key}: dimension ${d.key} declared twice`);
      keys.add(d.key);
      for (const g of d.groups) {
        if (mapped.has(g)) err(`profile ${m.key}: group "${g}" maps to both ${mapped.get(g)} and ${d.key}`);
        mapped.set(g, d.key);
      }
    }
    const observed = new Set(m.sheets.flatMap((s) => (wb.sheets[s.sheet]?.groups_observed || []).map((g) => g.group)));
    for (const g of observed) if (!mapped.has(g)) err(`profile ${m.key}: workbook group "${g}" maps to no dimension`);
    for (const g of mapped.keys()) if (!observed.has(g)) err(`profile ${m.key}: group "${g}" is not in the workbook (renamed or typo?)`);
  }

  /* ── overlays ── */
  const ruleIndexAll = ruleIndex;
  const dimsOf =Object.fromEntries([...moduleKeys].map((k) => [k, new Set((moduleDimensions(wb, k) || []).map((d) => d.key))]));
  for (const [key, sheet] of Object.entries(wb.sheets)) {
    const ov = wb.overlays[key];
    if (ov.workbook_sha256 !== sha) err(`overlays/${key}.json is stale: re-run scripts/health-workbook-overlays.mjs after the import`);
    for (const r of sheet.rules) {
      const e = ov.rules[r.id];
      if (!e) { err(`${r.id}: no overlay entry`); continue; }
      if (!moduleKeys.has(e.module)) err(`${r.id}: overlay module "${e.module}" is not a profile module`);
      if (e.dimension != null && !dimsOf[e.module]?.has(e.dimension)) err(`${r.id}: dimension "${e.dimension}" is not a ${e.module} dimension`);
      if (e.kind != null && !RULE_KINDS.includes(e.kind)) err(`${r.id}: kind "${e.kind}" is not one of ${RULE_KINDS.join(', ')}`);
      if (e.attainment != null && !ATTAINMENTS.includes(e.attainment)) err(`${r.id}: attainment "${e.attainment}" is not one of ${ATTAINMENTS.join(', ')}`);
      if (e.systemic_role != null && !SYSTEMIC_ROLES.includes(e.systemic_role)) err(`${r.id}: systemic_role "${e.systemic_role}" is not one of ${SYSTEMIC_ROLES.join(', ')}`);
      if (e.systemic_role != null && r.base_severity !== 'Systemic') err(`${r.id}: a Systemic role on a ${r.base_severity} rule (roles are declared for base-Systemic rules; escalation is decided at run time)`);
      if (!IMPLEMENTATION_STATES.includes(e.implementation?.state)) err(`${r.id}: implementation state "${e.implementation?.state}" is not one of ${IMPLEMENTATION_STATES.join(', ')}`);
      /* A block target is a rule (`rule:ID`), a module (`cmdb`) or a module dimension (`cmdb:D7`). */
      for (const b of e.blocks || []) {
        const [head, tail] = String(b).split(':');
        if (head === 'rule') { if (!ruleIndexAll.has(tail)) err(`${r.id}: blocks "${b}" names no workbook rule`); continue; }
        if (!moduleKeys.has(head)) { err(`${r.id}: blocks "${b}" names no module`); continue; }
        if (tail != null && !dimsOf[head]?.has(tail)) err(`${r.id}: blocks "${b}" names no ${head} dimension`);
      }
      for (const o of e.ownership || []) if (!wb.ownership.conditions.some((c) => c.id === o)) err(`${r.id}: ownership "${o}" is not in ownership.json`);
      if (key === 'cmdb' && e.equivalent_of && !ruleIndex.has(e.equivalent_of)) err(`${r.id}: equivalent_of ${e.equivalent_of} is not a workbook rule`);
      if (key === 'data-quality' && e.equivalent_of && !/^CMDB-\d{3}$/.test(e.equivalent_of)) err(`${r.id}: equivalent_of ${e.equivalent_of} is not a CMDB rule id`);
      if (!e.reviewed) pending.unreviewed_overlays += 1;
      /* A data-quality CMDB-model row restates a CMDB rule; its role is carried by that rule's entry. */
      const restated = key === 'data-quality' && e.module === 'cmdb';
      /* A correlation rule explains other findings and is not scored: it needs no Systemic role (Phase 2). */
      if (r.base_severity === 'Systemic' && e.systemic_role == null && !restated && e.kind !== 'correlation') pending.systemic_without_role.push(r.id);
    }
    for (const [id, e] of Object.entries(ov.rules)) {
      if (!sheet.rules.some((r) => r.id === id)) (e.orphan ? pending.orphans : errors).push(e.orphan ? id : `${id}: overlay entry for a rule not in sheet ${key}`);
    }
  }

  /* ── params ── */
  for (const [key, sheet] of Object.entries(wb.sheets)) {
    const p = wb.params[key];
    if (p.workbook_sha256 !== sha) err(`params/${key}.json is stale: re-run scripts/health-workbook-overlays.mjs after the import`);
    for (const r of sheet.rules) {
      const e = p.rules[r.id];
      if (!e) { err(`${r.id}: no parameter entry`); continue; }
      if (!PARAM_STATUSES.includes(e.status)) err(`${r.id}: parameter status "${e.status}"`);
      if (e.status === 'UNDECLARED') pending.undeclared_parameters += 1;
    }
  }

  /* ── ownership ── */
  for (const c of wb.ownership.conditions) {
    for (const m of c.members) {
      const hit = ruleIndex.get(m);
      if (!hit) { err(`${c.id}: member ${m} is not a workbook rule`); continue; }
      if (c.severities?.[m] && c.severities[m] !== hit.rule.base_severity) err(`${c.id}: records ${m} as ${c.severities[m]}; the workbook says ${hit.rule.base_severity}`);
    }
    if (c.proposed_owner != null && !c.members.includes(c.proposed_owner)) err(`${c.id}: proposed owner ${c.proposed_owner} is not a member`);
    if (c.status !== 'agreed') pending.open_ownership.push(c.id);
  }

  /* ── legacy map and decisions ── */
  for (const [id, m] of Object.entries(wb.legacyMap.rules)) {
    for (const w of m.workbook) if (!ruleIndex.has(w)) err(`legacy ${id}: workbook rule ${w} does not exist`);
    if (!wb.legacyMap.relations.includes(m.relation)) err(`legacy ${id}: relation "${m.relation}"`);
    if (!Object.keys(wb.legacyMap.dispositions).includes(m.disposition)) err(`legacy ${id}: disposition "${m.disposition}"`);
  }
  const decisionIds = new Set(wb.decisions.decisions.map((d) => d.id));
  if (wb.deviations) {
    for (const d of [...wb.deviations.implementation_only_rules, ...wb.deviations.cmdb_text_differences]) {
      if (d.decision && !decisionIds.has(d.decision)) err(`deviation ${d.rule_id}: decision ${d.decision} is not in decisions.json`);
    }
  }

  const pendingCount = pending.unreviewed_overlays + pending.systemic_without_role.length
    + pending.undeclared_parameters + pending.open_ownership.length + pending.orphans.length;
  if (strict && pendingCount) err(`strict: ${pendingCount} pending item(s) — see \`pending\``);

  return {
    ok: errors.length === 0,
    errors,
    pending,
    counts: Object.fromEntries(Object.entries(wb.sheets).map(([k, s]) => [k, s.rules.length])),
  };
}
