import { listFacts } from '../memory/facts.js';

/**
 * WI-5 — the trap check at PLAN time, before a human is asked to authorise
 * something the instance is going to discard.
 *
 * THE DEFECT THIS ANSWERS. Twice on 2026-08-24, a user approved
 * `{"priority":"4"}` on an incident and the platform stored `1` — priority is
 * computed from `impact` and `urgency`, and a direct write to it is accepted
 * and overwritten. Both times the read-back caught it AFTERWARDS and reported
 * `transformed`, which is the system working. But the approval had already been
 * spent: a person was asked to authorise a write the ledger already knew could
 * not land, and the fact that would have said so was sitting in the ledger the
 * whole time.
 *
 * So the check runs BEFORE the gate. It does not block and it does not
 * re-plan — it annotates the card the user is about to read, and puts the
 * ledger's own sentence into the model's next context so the re-plan it does
 * make is informed.
 *
 * TWO SOURCES, because one of them is measurably incomplete:
 *
 *   1. `mapping / calculated-fields:<table>` — written by schema discovery from
 *      the dictionary's own `calculated` / `read_only` flags.
 *   2. A short list of fields MEASURED to be derived that the dictionary does
 *      not flag. `incident.priority` is the whole reason this file exists and
 *      appears in none of the dictionary-derived lists — which is trap
 *      `dictionary-readonly-does-not-predict-rest-writes` restated: the
 *      dictionary flag does not predict what a REST write keeps.
 *
 * Each entry in (2) names the ledger fact that established it, and the warning
 * quotes that fact rather than paraphrasing it. If someone deletes the fact,
 * the check still fires and says the ledger no longer carries the evidence.
 */

/**
 * Fields this project has MEASURED to be derived, which the dictionary does not
 * mark. Every entry cites the ledger fact it came from — a claim in this table
 * with no fact behind it is a guess, and guesses are what the ledger exists to
 * replace.
 */
export const MEASURED_DERIVED = Object.freeze([
  {
    tables: ['task', 'incident', 'problem', 'change_request', 'sc_task', 'sc_req_item'],
    field: 'priority',
    drivers: ['impact', 'urgency'],
    factKey: 'priority-is-calculated',
  },
]);

/**
 * Read the field list back out of the sentence schema discovery wrote.
 *
 * Parsing prose is normally a smell; here the prose is generated by
 * `recordCalculatedFields` in this same repo with a fixed shape, and the test
 * round-trips that generator's real output rather than a fixture of it — so the
 * two cannot drift apart silently.
 */
export function parseCalculatedList(value) {
  const m = String(value || '').match(/accepted and then discarded:\s*([^.]+)\./i);
  if (!m) return [];
  return m[1].split(',').map((s) => s.trim()).filter(Boolean);
}

/**
 * @param {{ table: string, requested: object }} descriptor — the same shape the
 *   write guard and the verifier take, so all three agree on what is being sent.
 * @returns {null | { hits: Array, message: string, note: object }}
 */
export function planTimeTrapCheck({ table, requested } = {}, { facts = null } = {}) {
  // AN AID, NEVER A DEPENDENCY. Total by construction: a warning that can sink
  // the mutation it was added to annotate is worse than no warning, so every
  // path through the ledger is inside this.
  try { return computeTrapCheck({ table, requested }, facts); }
  catch { return null; }
}

function computeTrapCheck({ table, requested }, facts) {
  const fields = Object.keys(requested || {});
  if (!table || !fields.length) return null;

  const all = facts || listFacts();
  const hits = [];

  const calc = all.find((f) => f.kind === 'mapping' && f.key === `calculated-fields:${table}`);
  if (calc) {
    const listed = parseCalculatedList(calc.value);
    for (const field of fields) {
      if (listed.includes(field)) hits.push({ field, drivers: [], factKey: calc.key, fact: calc.value });
    }
  }

  for (const entry of MEASURED_DERIVED) {
    if (!entry.tables.includes(table)) continue;
    if (!fields.includes(entry.field)) continue;
    if (hits.some((h) => h.field === entry.field)) continue;
    const fact = all.find((f) => f.key === entry.factKey);
    hits.push({
      field: entry.field,
      drivers: entry.drivers,
      factKey: entry.factKey,
      fact: fact?.value || `(the ledger no longer carries "${entry.factKey}" — this was measured on this project)`,
    });
  }

  if (!hits.length) return null;

  const named = hits.map((h) => h.field);
  const drivers = [...new Set(hits.flatMap((h) => h.drivers))];
  const message =
    `${named.length === 1 ? `\`${named[0]}\` is` : `${named.map((f) => `\`${f}\``).join(', ')} are`} `
    + `calculated on \`${table}\`. The platform accepts this write and then overwrites it`
    + (drivers.length ? `; set ${drivers.map((d) => `\`${d}\``).join(' and ')} instead.` : '.');

  return {
    hits,
    message,
    // What goes into the model's next context: the ledger's own sentences, not
    // a summary of them.
    note: {
      planTimeWarning: message,
      fields: named,
      drive: drivers,
      knownFrom: hits.map((h) => ({ fact: h.factKey, says: h.fact })),
    },
  };
}
