import { ruleConfigFingerprint } from '../../itsm/rules/index.js';
import { ITOM } from '../pack.js';

/**
 * HEALTH ASSIST PHASE 5 — the ITOM rule configurations, validated exactly as the
 * ITSM ones (generated by scripts/build-itom-catalogue.mjs; loaded by the pack).
 * ITOM-001 / ITOM-002 have no configuration: they are CMDB rules' conditions (D-023).
 */
export const ITOM_RULE_CONFIGS = ITOM.configs;
export const itomRuleConfigFingerprint = () => ruleConfigFingerprint(ITOM_RULE_CONFIGS);
